title: Aaron Saray | Milwaukee Web Developer, PHP Programmer
description: Aaron Saray is a Milwaukee, Wisconsin Open Source Developer and Development Manager.
url: http://www.aaronsaray.com
timezone: America/Chicago

markdown: kramdown
permalink: /:year/:title
exclude: [README.md, workflow-tools, .DS_Store, LICENSE]

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
        - "/feed.xml"
        - "/css/main.css"
    include_posts:
        - "/blog.html"

sass:
    style: compressed
    
compress_html:
   clippings: all

tag_page_layout: page_tags
tag_page_dir: tag
tag_feed_layout: feed_tags
tag_feed_dir: tag
tag_page_data:
  sitemap: false
  
gems:
  - jekyll/tagging